### PR TITLE
Add running instructions to readme

### PR DESCRIPTION
**Pull request by ptere**
Should go through test on fresh machine before merging into master

### CODE REVIEW

**Comment by rwdaigle** [comment]
I don't think this is necessary. Can't you just open the `index.html` in your browser - you don't need an app server?

**Comment by ptere** [comment]
@rwdaigle Updated Readme to reflect that you can open in a browser. There’s a small CSS change to make it look the same as the hosted version.

**Comment by rwdaigle** [comment]
🚢

**Comment by ptere** [comment]
Merged & deployed in bf8c323.

**Pull request closed without merging**
